server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: giamdoc-service
app:
  cron: 0 0 0 15 * ?
  update-salary-of-nhan-vien-uri: http://nhanvien:8080/nhan-vien/update-salary
