/*
 * This file is generated by jOOQ.
 */
package com.vinorsoft.nhanvien.repository.generate;


import com.vinorsoft.nhanvien.repository.generate.tables.ChucVu;
import com.vinorsoft.nhanvien.repository.generate.tables.NhanVien;
import com.vinorsoft.nhanvien.repository.generate.tables.PhongBan;
import com.vinorsoft.nhanvien.repository.generate.tables.records.ChucVuRecord;
import com.vinorsoft.nhanvien.repository.generate.tables.records.NhanVienRecord;
import com.vinorsoft.nhanvien.repository.generate.tables.records.PhongBanRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * nhan_vien.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChucVuRecord> KEY_CHUC_VU_PRIMARY = Internal.createUniqueKey(ChucVu.CHUC_VU, DSL.name("KEY_chuc_vu_PRIMARY"), new TableField[]{ChucVu.CHUC_VU.CHUC_VU_ID}, true);
    public static final UniqueKey<ChucVuRecord> KEY_CHUC_VU_UK_8NY3M1SUPV5K5S1SXVHHHO88F = Internal.createUniqueKey(ChucVu.CHUC_VU, DSL.name("KEY_chuc_vu_UK_8ny3m1supv5k5s1sxvhhho88f"), new TableField[]{ChucVu.CHUC_VU.TEN_CHUC_VU}, true);
    public static final UniqueKey<NhanVienRecord> KEY_NHAN_VIEN_PRIMARY = Internal.createUniqueKey(NhanVien.NHAN_VIEN_, DSL.name("KEY_nhan_vien_PRIMARY"), new TableField[]{NhanVien.NHAN_VIEN_.ID}, true);
    public static final UniqueKey<NhanVienRecord> KEY_NHAN_VIEN_UK_12WAXXSINIYDDV2LT9IANFH8A = Internal.createUniqueKey(NhanVien.NHAN_VIEN_, DSL.name("KEY_nhan_vien_UK_12waxxsiniyddv2lt9ianfh8a"), new TableField[]{NhanVien.NHAN_VIEN_.EMAIL}, true);
    public static final UniqueKey<NhanVienRecord> KEY_NHAN_VIEN_UK_F0QENTJXCFEOYRWXPV5HTU514 = Internal.createUniqueKey(NhanVien.NHAN_VIEN_, DSL.name("KEY_nhan_vien_UK_f0qentjxcfeoyrwxpv5htu514"), new TableField[]{NhanVien.NHAN_VIEN_.MA_NHAN_VIEN}, true);
    public static final UniqueKey<NhanVienRecord> KEY_NHAN_VIEN_UK_MAFUWXHL2BCV6OBB9FKOUOKEC = Internal.createUniqueKey(NhanVien.NHAN_VIEN_, DSL.name("KEY_nhan_vien_UK_mafuwxhl2bcv6obb9fkouokec"), new TableField[]{NhanVien.NHAN_VIEN_.SDT}, true);
    public static final UniqueKey<PhongBanRecord> KEY_PHONG_BAN_PRIMARY = Internal.createUniqueKey(PhongBan.PHONG_BAN, DSL.name("KEY_phong_ban_PRIMARY"), new TableField[]{PhongBan.PHONG_BAN.PHONG_BAN_ID}, true);
    public static final UniqueKey<PhongBanRecord> KEY_PHONG_BAN_UK_87REOME3QODVJNX84F1OJIF94 = Internal.createUniqueKey(PhongBan.PHONG_BAN, DSL.name("KEY_phong_ban_UK_87reome3qodvjnx84f1ojif94"), new TableField[]{PhongBan.PHONG_BAN.TEN_PHONG_BAN}, true);
}
