/*
 * This file is generated by jOOQ.
 */
package com.vinorsoft.nhanvien.repository.generate;


import com.vinorsoft.nhanvien.repository.generate.tables.ChucVu;
import com.vinorsoft.nhanvien.repository.generate.tables.NhanVien;
import com.vinorsoft.nhanvien.repository.generate.tables.PhongBan;


/**
 * Convenience access to all tables in nhan_vien.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>nhan_vien.chuc_vu</code>.
     */
    public static final ChucVu CHUC_VU = ChucVu.CHUC_VU;

    /**
     * The table <code>nhan_vien.nhan_vien</code>.
     */
    public static final NhanVien NHAN_VIEN_ = NhanVien.NHAN_VIEN_;

    /**
     * The table <code>nhan_vien.phong_ban</code>.
     */
    public static final PhongBan PHONG_BAN = PhongBan.PHONG_BAN;
}
