/*
 * This file is generated by jOOQ.
 */
package com.vinorsoft.nhanvien.repository.generate.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ChucVu implements Serializable {

    private static final long serialVersionUID = 1L;

    private String chucVuId;
    private String tenChucVu;
    private String thamQuyen;

    public ChucVu() {
    }

    public ChucVu(ChucVu value) {
        this.chucVuId = value.chucVuId;
        this.tenChucVu = value.tenChucVu;
        this.thamQuyen = value.thamQuyen;
    }

    public ChucVu(
            String chucVuId,
            String tenChucVu,
            String thamQuyen
    ) {
        this.chucVuId = chucVuId;
        this.tenChucVu = tenChucVu;
        this.thamQuyen = thamQuyen;
    }

    /**
     * Getter for <code>nhan_vien.chuc_vu.chuc_vu_id</code>.
     */
    public String getChucVuId() {
        return this.chucVuId;
    }

    /**
     * Setter for <code>nhan_vien.chuc_vu.chuc_vu_id</code>.
     */
    public ChucVu setChucVuId(String chucVuId) {
        this.chucVuId = chucVuId;
        return this;
    }

    /**
     * Getter for <code>nhan_vien.chuc_vu.ten_chuc_vu</code>.
     */
    public String getTenChucVu() {
        return this.tenChucVu;
    }

    /**
     * Setter for <code>nhan_vien.chuc_vu.ten_chuc_vu</code>.
     */
    public ChucVu setTenChucVu(String tenChucVu) {
        this.tenChucVu = tenChucVu;
        return this;
    }

    /**
     * Getter for <code>nhan_vien.chuc_vu.tham_quyen</code>.
     */
    public String getThamQuyen() {
        return this.thamQuyen;
    }

    /**
     * Setter for <code>nhan_vien.chuc_vu.tham_quyen</code>.
     */
    public ChucVu setThamQuyen(String thamQuyen) {
        this.thamQuyen = thamQuyen;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ChucVu (");

        sb.append(chucVuId);
        sb.append(", ").append(tenChucVu);
        sb.append(", ").append(thamQuyen);

        sb.append(")");
        return sb.toString();
    }
}
