/*
 * This file is generated by jOOQ.
 */
package com.vinorsoft.nhanvien.repository.generate.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class NhanVien implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String chucVuId;
    private String email;
    private String hoVaTen;
    private Long luong;
    private String maNhanVien;
    private LocalDate ngaySinh;
    private String phongBanId;
    private String queQuan;
    private String sdt;
    private Byte trangThai;

    public NhanVien() {
    }

    public NhanVien(NhanVien value) {
        this.id = value.id;
        this.chucVuId = value.chucVuId;
        this.email = value.email;
        this.hoVaTen = value.hoVaTen;
        this.luong = value.luong;
        this.maNhanVien = value.maNhanVien;
        this.ngaySinh = value.ngaySinh;
        this.phongBanId = value.phongBanId;
        this.queQuan = value.queQuan;
        this.sdt = value.sdt;
        this.trangThai = value.trangThai;
    }

    public NhanVien(
            Integer id,
            String chucVuId,
            String email,
            String hoVaTen,
            Long luong,
            String maNhanVien,
            LocalDate ngaySinh,
            String phongBanId,
            String queQuan,
            String sdt,
            Byte trangThai
    ) {
        this.id = id;
        this.chucVuId = chucVuId;
        this.email = email;
        this.hoVaTen = hoVaTen;
        this.luong = luong;
        this.maNhanVien = maNhanVien;
        this.ngaySinh = ngaySinh;
        this.phongBanId = phongBanId;
        this.queQuan = queQuan;
        this.sdt = sdt;
        this.trangThai = trangThai;
    }

    /**
     * Getter for <code>nhan_vien.nhan_vien.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>nhan_vien.nhan_vien.id</code>.
     */
    public NhanVien setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>nhan_vien.nhan_vien.chuc_vu_id</code>.
     */
    public String getChucVuId() {
        return this.chucVuId;
    }

    /**
     * Setter for <code>nhan_vien.nhan_vien.chuc_vu_id</code>.
     */
    public NhanVien setChucVuId(String chucVuId) {
        this.chucVuId = chucVuId;
        return this;
    }

    /**
     * Getter for <code>nhan_vien.nhan_vien.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>nhan_vien.nhan_vien.email</code>.
     */
    public NhanVien setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>nhan_vien.nhan_vien.ho_va_ten</code>.
     */
    public String getHoVaTen() {
        return this.hoVaTen;
    }

    /**
     * Setter for <code>nhan_vien.nhan_vien.ho_va_ten</code>.
     */
    public NhanVien setHoVaTen(String hoVaTen) {
        this.hoVaTen = hoVaTen;
        return this;
    }

    /**
     * Getter for <code>nhan_vien.nhan_vien.luong</code>.
     */
    public Long getLuong() {
        return this.luong;
    }

    /**
     * Setter for <code>nhan_vien.nhan_vien.luong</code>.
     */
    public NhanVien setLuong(Long luong) {
        this.luong = luong;
        return this;
    }

    /**
     * Getter for <code>nhan_vien.nhan_vien.ma_nhan_vien</code>.
     */
    public String getMaNhanVien() {
        return this.maNhanVien;
    }

    /**
     * Setter for <code>nhan_vien.nhan_vien.ma_nhan_vien</code>.
     */
    public NhanVien setMaNhanVien(String maNhanVien) {
        this.maNhanVien = maNhanVien;
        return this;
    }

    /**
     * Getter for <code>nhan_vien.nhan_vien.ngay_sinh</code>.
     */
    public LocalDate getNgaySinh() {
        return this.ngaySinh;
    }

    /**
     * Setter for <code>nhan_vien.nhan_vien.ngay_sinh</code>.
     */
    public NhanVien setNgaySinh(LocalDate ngaySinh) {
        this.ngaySinh = ngaySinh;
        return this;
    }

    /**
     * Getter for <code>nhan_vien.nhan_vien.phong_ban_id</code>.
     */
    public String getPhongBanId() {
        return this.phongBanId;
    }

    /**
     * Setter for <code>nhan_vien.nhan_vien.phong_ban_id</code>.
     */
    public NhanVien setPhongBanId(String phongBanId) {
        this.phongBanId = phongBanId;
        return this;
    }

    /**
     * Getter for <code>nhan_vien.nhan_vien.que_quan</code>.
     */
    public String getQueQuan() {
        return this.queQuan;
    }

    /**
     * Setter for <code>nhan_vien.nhan_vien.que_quan</code>.
     */
    public NhanVien setQueQuan(String queQuan) {
        this.queQuan = queQuan;
        return this;
    }

    /**
     * Getter for <code>nhan_vien.nhan_vien.sdt</code>.
     */
    public String getSdt() {
        return this.sdt;
    }

    /**
     * Setter for <code>nhan_vien.nhan_vien.sdt</code>.
     */
    public NhanVien setSdt(String sdt) {
        this.sdt = sdt;
        return this;
    }

    /**
     * Getter for <code>nhan_vien.nhan_vien.trang_thai</code>.
     */
    public Byte getTrangThai() {
        return this.trangThai;
    }

    /**
     * Setter for <code>nhan_vien.nhan_vien.trang_thai</code>.
     */
    public NhanVien setTrangThai(Byte trangThai) {
        this.trangThai = trangThai;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("NhanVien (");

        sb.append(id);
        sb.append(", ").append(chucVuId);
        sb.append(", ").append(email);
        sb.append(", ").append(hoVaTen);
        sb.append(", ").append(luong);
        sb.append(", ").append(maNhanVien);
        sb.append(", ").append(ngaySinh);
        sb.append(", ").append(phongBanId);
        sb.append(", ").append(queQuan);
        sb.append(", ").append(sdt);
        sb.append(", ").append(trangThai);

        sb.append(")");
        return sb.toString();
    }
}
