/*
 * This file is generated by jOOQ.
 */
package com.vinorsoft.nhanvien.repository.generate.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PhongBan implements Serializable {

    private static final long serialVersionUID = 1L;

    private String phongBanId;
    private String chucNang;
    private String tenPhongBan;

    public PhongBan() {
    }

    public PhongBan(PhongBan value) {
        this.phongBanId = value.phongBanId;
        this.chucNang = value.chucNang;
        this.tenPhongBan = value.tenPhongBan;
    }

    public PhongBan(
            String phongBanId,
            String chucNang,
            String tenPhongBan
    ) {
        this.phongBanId = phongBanId;
        this.chucNang = chucNang;
        this.tenPhongBan = tenPhongBan;
    }

    /**
     * Getter for <code>nhan_vien.phong_ban.phong_ban_id</code>.
     */
    public String getPhongBanId() {
        return this.phongBanId;
    }

    /**
     * Setter for <code>nhan_vien.phong_ban.phong_ban_id</code>.
     */
    public PhongBan setPhongBanId(String phongBanId) {
        this.phongBanId = phongBanId;
        return this;
    }

    /**
     * Getter for <code>nhan_vien.phong_ban.chuc_nang</code>.
     */
    public String getChucNang() {
        return this.chucNang;
    }

    /**
     * Setter for <code>nhan_vien.phong_ban.chuc_nang</code>.
     */
    public PhongBan setChucNang(String chucNang) {
        this.chucNang = chucNang;
        return this;
    }

    /**
     * Getter for <code>nhan_vien.phong_ban.ten_phong_ban</code>.
     */
    public String getTenPhongBan() {
        return this.tenPhongBan;
    }

    /**
     * Setter for <code>nhan_vien.phong_ban.ten_phong_ban</code>.
     */
    public PhongBan setTenPhongBan(String tenPhongBan) {
        this.tenPhongBan = tenPhongBan;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PhongBan (");

        sb.append(phongBanId);
        sb.append(", ").append(chucNang);
        sb.append(", ").append(tenPhongBan);

        sb.append(")");
        return sb.toString();
    }
}
