/*
 * This file is generated by jOOQ.
 */
package com.vinorsoft.nhanvien.repository.generate.tables.records;


import com.vinorsoft.nhanvien.repository.generate.tables.ChucVu;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ChucVuRecord extends UpdatableRecordImpl<ChucVuRecord> implements Record3<String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached ChucVuRecord
     */
    public ChucVuRecord() {
        super(ChucVu.CHUC_VU);
    }

    /**
     * Create a detached, initialised ChucVuRecord
     */
    public ChucVuRecord(String chucVuId, String tenChucVu, String thamQuyen) {
        super(ChucVu.CHUC_VU);

        setChucVuId(chucVuId);
        setTenChucVu(tenChucVu);
        setThamQuyen(thamQuyen);
    }

    /**
     * Getter for <code>nhan_vien.chuc_vu.chuc_vu_id</code>.
     */
    public String getChucVuId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>nhan_vien.chuc_vu.chuc_vu_id</code>.
     */
    public ChucVuRecord setChucVuId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>nhan_vien.chuc_vu.ten_chuc_vu</code>.
     */
    public String getTenChucVu() {
        return (String) get(1);
    }

    /**
     * Setter for <code>nhan_vien.chuc_vu.ten_chuc_vu</code>.
     */
    public ChucVuRecord setTenChucVu(String value) {
        set(1, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>nhan_vien.chuc_vu.tham_quyen</code>.
     */
    public String getThamQuyen() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>nhan_vien.chuc_vu.tham_quyen</code>.
     */
    public ChucVuRecord setThamQuyen(String value) {
        set(2, value);
        return this;
    }

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    @Override
    public Row3<String, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return ChucVu.CHUC_VU.CHUC_VU_ID;
    }

    @Override
    public Field<String> field2() {
        return ChucVu.CHUC_VU.TEN_CHUC_VU;
    }

    @Override
    public Field<String> field3() {
        return ChucVu.CHUC_VU.THAM_QUYEN;
    }

    @Override
    public String component1() {
        return getChucVuId();
    }

    @Override
    public String component2() {
        return getTenChucVu();
    }

    @Override
    public String component3() {
        return getThamQuyen();
    }

    @Override
    public String value1() {
        return getChucVuId();
    }

    @Override
    public String value2() {
        return getTenChucVu();
    }

    @Override
    public String value3() {
        return getThamQuyen();
    }

    @Override
    public ChucVuRecord value1(String value) {
        setChucVuId(value);
        return this;
    }

    @Override
    public ChucVuRecord value2(String value) {
        setTenChucVu(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public ChucVuRecord value3(String value) {
        setThamQuyen(value);
        return this;
    }

    @Override
    public ChucVuRecord values(String value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
