/*
 * This file is generated by jOOQ.
 */
package com.vinorsoft.nhanvien.repository.generate.tables.records;


import com.vinorsoft.nhanvien.repository.generate.tables.NhanVien;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class NhanVienRecord extends UpdatableRecordImpl<NhanVienRecord> implements Record11<Integer, String, String, String, Double, String, LocalDate, String, String, String, Byte> {

    private static final long serialVersionUID = 1L;

    /**
     * Create a detached NhanVienRecord
     */
    public NhanVienRecord() {
        super(NhanVien.NHAN_VIEN_);
    }

    /**
     * Create a detached, initialised NhanVienRecord
     */
    public NhanVienRecord(Integer id, String chucVuId, String email, String hoVaTen, Double luong, String maNhanVien, LocalDate ngaySinh, String phongBanId, String queQuan, String sdt, Byte trangThai) {
        super(NhanVien.NHAN_VIEN_);

        setId(id);
        setChucVuId(chucVuId);
        setEmail(email);
        setHoVaTen(hoVaTen);
        setLuong(luong);
        setMaNhanVien(maNhanVien);
        setNgaySinh(ngaySinh);
        setPhongBanId(phongBanId);
        setQueQuan(queQuan);
        setSdt(sdt);
        setTrangThai(trangThai);
    }

    /**
     * Getter for <code>nhan_vien.nhan_vien.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>nhan_vien.nhan_vien.id</code>.
     */
    public NhanVienRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>nhan_vien.nhan_vien.chuc_vu_id</code>.
     */
    public String getChucVuId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>nhan_vien.nhan_vien.chuc_vu_id</code>.
     */
    public NhanVienRecord setChucVuId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>nhan_vien.nhan_vien.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>nhan_vien.nhan_vien.email</code>.
     */
    public NhanVienRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>nhan_vien.nhan_vien.ho_va_ten</code>.
     */
    public String getHoVaTen() {
        return (String) get(3);
    }

    /**
     * Setter for <code>nhan_vien.nhan_vien.ho_va_ten</code>.
     */
    public NhanVienRecord setHoVaTen(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>nhan_vien.nhan_vien.luong</code>.
     */
    public Double getLuong() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>nhan_vien.nhan_vien.luong</code>.
     */
    public NhanVienRecord setLuong(Double value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>nhan_vien.nhan_vien.ma_nhan_vien</code>.
     */
    public String getMaNhanVien() {
        return (String) get(5);
    }

    /**
     * Setter for <code>nhan_vien.nhan_vien.ma_nhan_vien</code>.
     */
    public NhanVienRecord setMaNhanVien(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>nhan_vien.nhan_vien.ngay_sinh</code>.
     */
    public LocalDate getNgaySinh() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>nhan_vien.nhan_vien.ngay_sinh</code>.
     */
    public NhanVienRecord setNgaySinh(LocalDate value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>nhan_vien.nhan_vien.phong_ban_id</code>.
     */
    public String getPhongBanId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>nhan_vien.nhan_vien.phong_ban_id</code>.
     */
    public NhanVienRecord setPhongBanId(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>nhan_vien.nhan_vien.que_quan</code>.
     */
    public String getQueQuan() {
        return (String) get(8);
    }

    /**
     * Setter for <code>nhan_vien.nhan_vien.que_quan</code>.
     */
    public NhanVienRecord setQueQuan(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>nhan_vien.nhan_vien.sdt</code>.
     */
    public String getSdt() {
        return (String) get(9);
    }

    /**
     * Setter for <code>nhan_vien.nhan_vien.sdt</code>.
     */
    public NhanVienRecord setSdt(String value) {
        set(9, value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>nhan_vien.nhan_vien.trang_thai</code>.
     */
    public Byte getTrangThai() {
        return (Byte) get(10);
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>nhan_vien.nhan_vien.trang_thai</code>.
     */
    public NhanVienRecord setTrangThai(Byte value) {
        set(10, value);
        return this;
    }

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    @Override
    public Row11<Integer, String, String, String, Double, String, LocalDate, String, String, String, Byte> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Integer, String, String, String, Double, String, LocalDate, String, String, String, Byte> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return NhanVien.NHAN_VIEN_.ID;
    }

    @Override
    public Field<String> field2() {
        return NhanVien.NHAN_VIEN_.CHUC_VU_ID;
    }

    @Override
    public Field<String> field3() {
        return NhanVien.NHAN_VIEN_.EMAIL;
    }

    @Override
    public Field<String> field4() {
        return NhanVien.NHAN_VIEN_.HO_VA_TEN;
    }

    @Override
    public Field<Double> field5() {
        return NhanVien.NHAN_VIEN_.LUONG;
    }

    @Override
    public Field<String> field6() {
        return NhanVien.NHAN_VIEN_.MA_NHAN_VIEN;
    }

    @Override
    public Field<LocalDate> field7() {
        return NhanVien.NHAN_VIEN_.NGAY_SINH;
    }

    @Override
    public Field<String> field8() {
        return NhanVien.NHAN_VIEN_.PHONG_BAN_ID;
    }

    @Override
    public Field<String> field9() {
        return NhanVien.NHAN_VIEN_.QUE_QUAN;
    }

    @Override
    public Field<String> field10() {
        return NhanVien.NHAN_VIEN_.SDT;
    }

    @Override
    public Field<Byte> field11() {
        return NhanVien.NHAN_VIEN_.TRANG_THAI;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getChucVuId();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public String component4() {
        return getHoVaTen();
    }

    @Override
    public Double component5() {
        return getLuong();
    }

    @Override
    public String component6() {
        return getMaNhanVien();
    }

    @Override
    public LocalDate component7() {
        return getNgaySinh();
    }

    @Override
    public String component8() {
        return getPhongBanId();
    }

    @Override
    public String component9() {
        return getQueQuan();
    }

    @Override
    public String component10() {
        return getSdt();
    }

    @Override
    public Byte component11() {
        return getTrangThai();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getChucVuId();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public String value4() {
        return getHoVaTen();
    }

    @Override
    public Double value5() {
        return getLuong();
    }

    @Override
    public String value6() {
        return getMaNhanVien();
    }

    @Override
    public LocalDate value7() {
        return getNgaySinh();
    }

    @Override
    public String value8() {
        return getPhongBanId();
    }

    @Override
    public String value9() {
        return getQueQuan();
    }

    @Override
    public String value10() {
        return getSdt();
    }

    @Override
    public Byte value11() {
        return getTrangThai();
    }

    @Override
    public NhanVienRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public NhanVienRecord value2(String value) {
        setChucVuId(value);
        return this;
    }

    @Override
    public NhanVienRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public NhanVienRecord value4(String value) {
        setHoVaTen(value);
        return this;
    }

    @Override
    public NhanVienRecord value5(Double value) {
        setLuong(value);
        return this;
    }

    @Override
    public NhanVienRecord value6(String value) {
        setMaNhanVien(value);
        return this;
    }

    @Override
    public NhanVienRecord value7(LocalDate value) {
        setNgaySinh(value);
        return this;
    }

    @Override
    public NhanVienRecord value8(String value) {
        setPhongBanId(value);
        return this;
    }

    @Override
    public NhanVienRecord value9(String value) {
        setQueQuan(value);
        return this;
    }

    @Override
    public NhanVienRecord value10(String value) {
        setSdt(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public NhanVienRecord value11(Byte value) {
        setTrangThai(value);
        return this;
    }

    @Override
    public NhanVienRecord values(Integer value1, String value2, String value3, String value4, Double value5, String value6, LocalDate value7, String value8, String value9, String value10, Byte value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }
}
