server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/nhan_vien
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update