/*
 * This file is generated by jOOQ.
 */
package com.vinorsoft.nhanvien.repository.generate.tables.daos;


import com.vinorsoft.nhanvien.repository.generate.tables.ChucVu;
import com.vinorsoft.nhanvien.repository.generate.tables.records.ChucVuRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ChucVuDao extends DAOImpl<ChucVuRecord, com.vinorsoft.nhanvien.repository.generate.tables.pojos.ChucVu, String> {

    /**
     * Create a new ChucVuDao without any configuration
     */
    public ChucVuDao() {
        super(ChucVu.CHUC_VU, com.vinorsoft.nhanvien.repository.generate.tables.pojos.ChucVu.class);
    }

    /**
     * Create a new ChucVuDao with an attached configuration
     */
    public ChucVuDao(Configuration configuration) {
        super(ChucVu.CHUC_VU, com.vinorsoft.nhanvien.repository.generate.tables.pojos.ChucVu.class, configuration);
    }

    @Override
    public String getId(com.vinorsoft.nhanvien.repository.generate.tables.pojos.ChucVu object) {
        return object.getChucVuId();
    }

    /**
     * Fetch records that have <code>chuc_vu_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.vinorsoft.nhanvien.repository.generate.tables.pojos.ChucVu> fetchRangeOfChucVuId(String lowerInclusive, String upperInclusive) {
        return fetchRange(ChucVu.CHUC_VU.CHUC_VU_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>chuc_vu_id IN (values)</code>
     */
    public List<com.vinorsoft.nhanvien.repository.generate.tables.pojos.ChucVu> fetchByChucVuId(String... values) {
        return fetch(ChucVu.CHUC_VU.CHUC_VU_ID, values);
    }

    /**
     * Fetch a unique record that has <code>chuc_vu_id = value</code>
     */
    public com.vinorsoft.nhanvien.repository.generate.tables.pojos.ChucVu fetchOneByChucVuId(String value) {
        return fetchOne(ChucVu.CHUC_VU.CHUC_VU_ID, value);
    }

    /**
     * Fetch records that have <code>ten_chuc_vu BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.vinorsoft.nhanvien.repository.generate.tables.pojos.ChucVu> fetchRangeOfTenChucVu(String lowerInclusive, String upperInclusive) {
        return fetchRange(ChucVu.CHUC_VU.TEN_CHUC_VU, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ten_chuc_vu IN (values)</code>
     */
    public List<com.vinorsoft.nhanvien.repository.generate.tables.pojos.ChucVu> fetchByTenChucVu(String... values) {
        return fetch(ChucVu.CHUC_VU.TEN_CHUC_VU, values);
    }

    /**
     * Fetch a unique record that has <code>ten_chuc_vu = value</code>
     */
    public com.vinorsoft.nhanvien.repository.generate.tables.pojos.ChucVu fetchOneByTenChucVu(String value) {
        return fetchOne(ChucVu.CHUC_VU.TEN_CHUC_VU, value);
    }

    /**
     * Fetch records that have <code>tham_quyen BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.vinorsoft.nhanvien.repository.generate.tables.pojos.ChucVu> fetchRangeOfThamQuyen(String lowerInclusive, String upperInclusive) {
        return fetchRange(ChucVu.CHUC_VU.THAM_QUYEN, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>tham_quyen IN (values)</code>
     */
    public List<com.vinorsoft.nhanvien.repository.generate.tables.pojos.ChucVu> fetchByThamQuyen(String... values) {
        return fetch(ChucVu.CHUC_VU.THAM_QUYEN, values);
    }
}
